# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adzz
email: lancaster28@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog of Adam Lancaster, aspiring software craftsman.
baseurl: /
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ItizAdz
github_username:  Adzz
author:
  name:           'Adam Lancaster'
  url:            https://twitter.com/itizadz
paginate:         5
permalink:        pretty
disqus:
  shortname: adzz
sass:
  style: compressed
# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins: [jekyll-paginate, jekyll-gist, jekyll-seo-tag]
github:
  repo:           https://github.com/adzz
# XML feed
name: Adzz
description: My insights into the world of code
url: adzz.github.io
