# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adzz
email: lancaster28@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Will code for money.
baseurl: /
name: Adzz
url: adzz.github.io
twitter_username: ItizAdz
github_username:  Adzz
author:
  name:           'Adam Lancaster'
  url:            https://twitter.com/itizadz
paginate:         5
permalink:        pretty
disqus:
  shortname: adzz
sass:
  style: compressed
markdown:         redcarpet
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist, jekyll-seo-tag]
github:
  repo:           https://github.com/adzz
